<!--
  UComarkEditor.vue — project-internal Nuxt UI integration for the
  framework-agnostic `<ComarkEditor>` from `tiptap-comark-vue`.

  Why this lives in `app/components/` and not in `lib/`:

  - `tiptap-comark-vue` is intentionally un-opinionated — it ships no
    visual prose styling so it can be dropped into any Vue / Nuxt app
    without conflicting with the host's design system.
  - Nuxt UI v4 ships its own editor theme entry at `#build/ui/editor`
    (auto-generated by the `@nuxt/ui` Nuxt module). It's the same
    entry `<UEditor>` itself consumes, so reusing it here gives our
    Comark-based editor visual parity with Nuxt UI's stock editor
    without depending on `@tailwindcss/typography` (which Tailwind v4
    + Nuxt UI prefer to side-step in favor of their own Prose system).
  - This wrapper is a *demonstration* of the integration shape. A
    published `tiptap-comark-nuxt-ui` package would look almost
    identical — the only reason it isn't one yet is that the API
    surface is still settling.

  How the styling reaches the editor: Nuxt UI's `tv()`-built theme
  yields three slot class strings — `root` (outer wrapper), `content`
  (the `<EditorContent>` host element), and `base` (the actual
  `.ProseMirror` contenteditable). The `base` slot carries every
  `[&_h1]:text-3xl`, `[&_blockquote]:…`, `[&_ul]:list-disc`, … rule;
  it lands on `.ProseMirror` via `editorOptions.editorProps.attributes.class`,
  which is the same channel `<UEditor>` uses internally (see Nuxt UI's
  Editor.vue). Descendant `[&_…]` selectors then style every prose
  element inside the editor.

  The kit's own operational CSS (`tiptap-comark`'s `injectStyles`)
  composes cleanly with this: kit selectors target `[data-comark-*]`
  with a `:not([data-node-view-wrapper])` carve-out, Nuxt UI's editor
  theme targets standard prose tags. No collision, no override war.
-->

<script setup lang="ts">
import { computed, useAttrs, type ComputedRef } from 'vue'
import defu from 'defu'
import { Primitive } from 'reka-ui'
import editorTheme from '#build/ui/editor'
import { tv } from '@nuxt/ui/runtime/utils/tv.js'
import { useComponentUI } from '@nuxt/ui/composables'
import { useAppConfig } from '#imports'
import { ComarkEditor, type Editor } from 'tiptap-comark-vue'
import type {
  ComarkTree,
  ComarkVueComponentExports,
  JSONContent,
  UseComarkEditorOptions,
} from 'tiptap-comark-vue'
import type { AnyExtension } from '@tiptap/core'

interface UiSlots {
  root?: string
  content?: string
  base?: string
}

interface Props {
  /** Inherits `<ComarkEditor>`'s seed/v-model surface verbatim. */
  initial?: ComarkTree | JSONContent | string
  ast?: ComarkTree
  markdown?: string
  json?: JSONContent
  components?: ReadonlyArray<ComarkVueComponentExports>
  extensions?: ReadonlyArray<AnyExtension>
  editorOptions?: UseComarkEditorOptions['editorOptions']
  /** Outer wrapper element. Mirrors `<UEditor>`'s `as` prop. */
  as?: string
  /** Class applied to the outer wrapper (Nuxt UI convention). */
  class?: string
  /** Per-instance slot-class overrides — same shape as `<UEditor>`'s `ui` prop. */
  ui?: UiSlots
  /** Forwarded to the editor theme's `placeholderMode` variant. */
  placeholderMode?: 'firstLine' | 'everyLine'
}

const props = withDefaults(defineProps<Props>(), {
  as: 'div',
})

const emits = defineEmits<{
  'update:ast': [tree: ComarkTree]
  'update:markdown': [markdown: string]
  'update:json': [json: JSONContent]
  'ready': [editor: Editor]
  'update': [editor: Editor]
}>()

defineSlots<{
  default(props: { editor: Editor | undefined; isReady: boolean }): unknown
  fallback(): unknown
}>()

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()
const appConfig = useAppConfig()

// Same composition `<UEditor>` itself does: extend the auto-generated
// theme entry with any project-level `appConfig.ui.editor` overrides,
// then bind `placeholderMode` from props. `tv` is Nuxt UI's `createTV`
// instance, configured with the project's `appConfig.ui.tv`.
//
// The type assertions here paper over a typing gap, not a runtime one:
// `#build/ui/editor` is auto-generated and lands as a loose object,
// so `tv()` can't infer the `{ root, base, content }` slots or the
// `placeholderMode` variant. Nuxt UI's own `<UEditor>` types live
// inside its build pipeline and aren't re-exported. The shapes below
// match the runtime contract one-to-one.
type EditorTv = (variants?: { placeholderMode?: 'firstLine' | 'everyLine' }) => {
  root: (opts?: { class?: unknown }) => string
  base: (opts?: { class?: unknown }) => string
  content: (opts?: { class?: unknown }) => string
}
// `useComponentUI` returns a `ComputedRef<UiSlots | undefined>`; the
// cast tells volar so template-level `uiProp?.root` auto-unwraps to
// the slot string.
const uiProp = useComponentUI('editor', props) as unknown as ComputedRef<UiSlots | undefined>
const ui = computed(() => {
  const editorOverrides = (appConfig.ui as { editor?: object } | undefined)?.editor
  const tvFn = tv({ extend: tv(editorTheme), ...editorOverrides }) as unknown as EditorTv
  return tvFn({ placeholderMode: props.placeholderMode })
})

// The `[&_h1]:…` / `[&_ul]:list-disc` / etc. variants live on `base`,
// which Nuxt UI applies to the `.ProseMirror` contenteditable element
// via `editorProps.attributes.class`. We do the same here by merging
// into `editorOptions.editorProps.attributes` so any `editorOptions`
// the consumer passed in is preserved.
const editorOptions = computed<UseComarkEditorOptions['editorOptions']>(() =>
  defu(props.editorOptions, {
    editorProps: {
      attributes: {
        class: ui.value.base({ class: uiProp.value?.base }),
      },
    },
  }),
)

// Forward $attrs (incl. `data-test`, ARIA, native handlers) onto the
// `<EditorContent>` host through `<ComarkEditor>`'s $attrs passthrough,
// alongside the theme's `content` class.
const contentBindings = computed(() => ({
  ...attrs,
  class: ui.value.content({ class: uiProp.value?.content }),
}))
</script>

<template>
  <Primitive :as="as" data-slot="root" :class="ui.root({ class: [uiProp?.root, props.class] })">
    <ComarkEditor
      :ast="props.ast"
      :markdown="props.markdown"
      :json="props.json"
      :initial="props.initial"
      :components="props.components"
      :extensions="props.extensions"
      :editor-options="editorOptions"
      v-bind="contentBindings"
      @update:ast="(tree) => emits('update:ast', tree)"
      @update:markdown="(md) => emits('update:markdown', md)"
      @update:json="(json) => emits('update:json', json)"
      @ready="(e) => emits('ready', e)"
      @update="(e) => emits('update', e)"
    >
      <template #default="slotProps">
        <slot v-bind="slotProps" />
      </template>
      <template #fallback>
        <slot name="fallback" />
      </template>
    </ComarkEditor>
  </Primitive>
</template>
